### ISSUE TITLE
Installation failed on macOS 10.12.6

### ISSUE THREAD

**Issue by jzgdev** [nodepy/nodepy#71] opened 2017-10-20 10:59 UTC
Tried `pip install node.py` on python 2.7.10 and python 3.6.3 but keep getting

`Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-build-SZfMwN/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-_NsF_T-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-build-SZfMwN/node.py/`

Afterwards, I do seem to be able to run "nodepy" from terminal, but it doesn't seem to work quite right, also nppm is unavailable.

**Comment by NiklasRosenstein** [comment] 2017-10-20 11:56
Is there an exception traceback? It looks a lot like https://github.com/pypa/pip/issues/373 -- The fix for that has not been integrated into a new Pip version yet.

**Comment by jzgdev** [comment] 2017-10-21 00:07
Here is the full output:

```
Collecting node.py
  Using cached node.py-0.0.22.tar.gz
Collecting colorama>=0.3.9 (from node.py)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting localimport>=1.5.1 (from node.py)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/site-packages (from node.py)
Requirement already satisfied: pip>=8.0.0 in /usr/local/lib/python2.7/site-packages (from node.py)
Collecting wheel>=0.29.0 (from node.py)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Installing collected packages: colorama, localimport, wheel, node.py
  Running setup.py install for node.py ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-build-SZfMwN/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-_NsF_T-record/install-record.txt --single-version-externally-managed --compile:
    running install
    Installing Node.py and Node.py-PM dependencies in a separate context ...
      Command: pip install colorama>=0.3.9 localimport>=1.5.1 six>=1.10.0 pip>=8.0.0 wheel>=0.29.0
    Requirement already satisfied: colorama>=0.3.9 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
    Requirement already satisfied: localimport>=1.5.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
    Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/site-packages
    Requirement already satisfied: pip>=8.0.0 in /usr/local/lib/python2.7/site-packages
    Requirement already satisfied: wheel>=0.29.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
    running build
    running build_py
    creating build
    creating build/lib
    copying nodepy.py -> build/lib
    running install_lib
    copying build/lib/nodepy.py -> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
    byte-compiling /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nodepy.py to nodepy.pyc
    running install_egg_info
    running egg_info
    writing requirements to node.py.egg-info/requires.txt
    writing node.py.egg-info/PKG-INFO
    writing top-level names to node.py.egg-info/top_level.txt
    writing dependency_links to node.py.egg-info/dependency_links.txt
    writing entry points to node.py.egg-info/entry_points.txt
    reading manifest file 'node.py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'nppm/dist'
    no previously-included directories found matching 'nppm/nodepy_modules'
    writing manifest file 'node.py.egg-info/SOURCES.txt'
    Copying node.py.egg-info to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/node.py-0.0.22-py2.7.egg-info
    running install_scripts
    Installing nodepy2 script to /Library/Frameworks/Python.framework/Versions/2.7/bin
    Installing nodepy script to /Library/Frameworks/Python.framework/Versions/2.7/bin
    Installing nodepy2.7 script to /Library/Frameworks/Python.framework/Versions/2.7/bin
    writing list of installed files to '/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-_NsF_T-record/install-record.txt'
    Bootstrapping NPPM dependencies with Pip ...
    ('$ pip install', u'--target nodepy_modules/.pip/lib/python2.7/site-packages distlib>=0.2.4 hammock>=0.2.4 jsonschema>=2.6.0 requests>=2.13.0 click>=6.7 appdirs>=1.4.2')
    Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
          [install] prefix=
    Collecting distlib>=0.2.4
    Collecting hammock>=0.2.4
    Collecting jsonschema>=2.6.0
      Using cached jsonschema-2.6.0-py2.py3-none-any.whl
    Collecting requests>=2.13.0
      Using cached requests-2.18.4-py2.py3-none-any.whl
    Collecting click>=6.7
      Using cached click-6.7-py2.py3-none-any.whl
    Collecting appdirs>=1.4.2
      Using cached appdirs-1.4.3-py2.py3-none-any.whl
    Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0)
    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0)
      Using cached chardet-3.0.4-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests>=2.13.0)
      Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0)
      Using cached urllib3-1.22-py2.py3-none-any.whl
    Collecting idna<2.7,>=2.5 (from requests>=2.13.0)
      Using cached idna-2.6-py2.py3-none-any.whl
    Installing collected packages: distlib, chardet, certifi, urllib3, idna, requests, hammock, functools32, jsonschema, click, appdirs
    Successfully installed appdirs-1.4.3 certifi-2017.7.27.1 chardet-3.0.4 click-6.7 distlib-0.2.5 functools32-3.2.3.post2 hammock-0.2.4 idna-2.6 jsonschema-2.6.0 requests-2.18.4 urllib3-1.22
    Installing NPPM (install --ignore-installed --upgrade --root /private/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-build-SZfMwN/node.py/nppm --pip-separate-process) ...
    Installing "@nodepy/nppm@0.0.22"...
    Installing Python dependencies for "@nodepy/nppm@0.0.22"...
      Installing Python dependencies via Pip: distlib>=0.2.4 hammock>=0.2.4 jsonschema>=2.6.0 requests>=2.13.0 click>=6.7 appdirs>=1.4.2 --ignore-installed --upgrade (as a separate process)
    Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
          [install] prefix=
    Collecting distlib>=0.2.4
    Collecting hammock>=0.2.4
    Collecting jsonschema>=2.6.0
      Using cached jsonschema-2.6.0-py2.py3-none-any.whl
    Collecting requests>=2.13.0
      Using cached requests-2.18.4-py2.py3-none-any.whl
    Collecting click>=6.7
      Using cached click-6.7-py2.py3-none-any.whl
    Collecting appdirs>=1.4.2
      Using cached appdirs-1.4.3-py2.py3-none-any.whl
    Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0)
    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0)
      Using cached chardet-3.0.4-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests>=2.13.0)
      Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0)
      Using cached urllib3-1.22-py2.py3-none-any.whl
    Collecting idna<2.7,>=2.5 (from requests>=2.13.0)
      Using cached idna-2.6-py2.py3-none-any.whl
    Installing collected packages: distlib, chardet, certifi, urllib3, idna, requests, hammock, functools32, jsonschema, click, appdirs
    Exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
        prefix=options.prefix_path,
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 492, in move_wheel_files
        maker.make_multiple(['%s = %s' % kv for kv in console.items()])
      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
        filenames.extend(self.make(specification, options))
      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
        self._make_script(entry, filenames, options=options)
      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
        self._write_script(scriptnames, shebang, script, filenames, ext)
      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
        self._fileop.write_binary_file(outname, script_bytes)
      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 407, in write_binary_file
        with open(path, 'wb') as f:
    IOError: [Errno 1] Operation not permitted: '/bin/chardetect'
    Error: `pip install` failed with exit-code 2
    Error: Installation failed
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-build-SZfMwN/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-_NsF_T-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/w9/x9_w1ky97n7frgm5qj81kf780000gn/T/pip-build-SZfMwN/node.py/
```

**Comment by NiklasRosenstein** [comment] 2017-10-21 11:40
Thanks for the output. Seems you're installing into the system's site. Did you use `sudo` to install Node.py?

**Comment by jzgdev** [comment] 2017-11-01 22:24
Uninstalled node.py and tried again running `sudo pip install node.py`, still failed, here's the output:

	Collecting node.py
	  Downloading node.py-0.0.22.tar.gz (59kB)
	    100% |████████████████████████████████| 61kB 989kB/s 
	Requirement already satisfied: colorama>=0.3.9 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from node.py)
	Requirement already satisfied: localimport>=1.5.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from node.py)
	Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/site-packages (from node.py)
	Requirement already satisfied: pip>=8.0.0 in /usr/local/lib/python2.7/site-packages (from node.py)
	Requirement already satisfied: wheel>=0.29.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from node.py)
	Installing collected packages: node.py
	  Running setup.py install for node.py ... error
	    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-jkLq8A/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-I0O_1Q-record/install-record.txt --single-version-externally-managed --compile:
	    running install
	    Installing Node.py and Node.py-PM dependencies in a separate context ...
	      Command: pip install colorama>=0.3.9 localimport>=1.5.1 six>=1.10.0 pip>=8.0.0 wheel>=0.29.0
	    The directory '/Users/Alex/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	    The directory '/Users/Alex/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	    Requirement already satisfied: colorama>=0.3.9 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
	    Requirement already satisfied: localimport>=1.5.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
	    Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python2.7/site-packages
	    Requirement already satisfied: pip>=8.0.0 in /usr/local/lib/python2.7/site-packages
	    Requirement already satisfied: wheel>=0.29.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
	    running build
	    running build_py
	    creating build
	    creating build/lib
	    copying nodepy.py -> build/lib
	    running install_lib
	    copying build/lib/nodepy.py -> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
	    byte-compiling /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nodepy.py to nodepy.pyc
	    running install_egg_info
	    running egg_info
	    writing requirements to node.py.egg-info/requires.txt
	    writing node.py.egg-info/PKG-INFO
	    writing top-level names to node.py.egg-info/top_level.txt
	    writing dependency_links to node.py.egg-info/dependency_links.txt
	    writing entry points to node.py.egg-info/entry_points.txt
	    reading manifest file 'node.py.egg-info/SOURCES.txt'
	    reading manifest template 'MANIFEST.in'
	    no previously-included directories found matching 'nppm/dist'
	    no previously-included directories found matching 'nppm/nodepy_modules'
	    writing manifest file 'node.py.egg-info/SOURCES.txt'
	    Copying node.py.egg-info to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/node.py-0.0.22-py2.7.egg-info
	    running install_scripts
	    Installing nodepy2 script to /Library/Frameworks/Python.framework/Versions/2.7/bin
	    Installing nodepy script to /Library/Frameworks/Python.framework/Versions/2.7/bin
	    Installing nodepy2.7 script to /Library/Frameworks/Python.framework/Versions/2.7/bin
	    writing list of installed files to '/tmp/pip-I0O_1Q-record/install-record.txt'
	    Bootstrapping NPPM dependencies with Pip ...
	    ('$ pip install', u'--target nodepy_modules/.pip/lib/python2.7/site-packages distlib>=0.2.4 hammock>=0.2.4 jsonschema>=2.6.0 requests>=2.13.0 click>=6.7 appdirs>=1.4.2')
	    Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
	          [install] prefix=
	    The directory '/Users/Alex/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	    The directory '/Users/Alex/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	    Collecting distlib>=0.2.4
	      Downloading distlib-0.2.6.zip (558kB)
	    Collecting hammock>=0.2.4
	      Downloading hammock-0.2.4.tar.gz
	    Collecting jsonschema>=2.6.0
	      Downloading jsonschema-2.6.0-py2.py3-none-any.whl
	    Collecting requests>=2.13.0
	      Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
	    Collecting click>=6.7
	      Downloading click-6.7-py2.py3-none-any.whl (71kB)
	    Collecting appdirs>=1.4.2
	      Downloading appdirs-1.4.3-py2.py3-none-any.whl
	    Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0)
	      Downloading functools32-3.2.3-2.zip
	    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0)
	      Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
	    Collecting certifi>=2017.4.17 (from requests>=2.13.0)
	      Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
	    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0)
	      Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
	    Collecting idna<2.7,>=2.5 (from requests>=2.13.0)
	      Downloading idna-2.6-py2.py3-none-any.whl (56kB)
	    Installing collected packages: distlib, chardet, certifi, urllib3, idna, requests, hammock, functools32, jsonschema, click, appdirs
	      Running setup.py install for distlib: started
	        Running setup.py install for distlib: finished with status 'done'
	      Running setup.py install for hammock: started
	        Running setup.py install for hammock: finished with status 'done'
	      Running setup.py install for functools32: started
	        Running setup.py install for functools32: finished with status 'done'
	    Successfully installed appdirs-1.4.3 certifi-2017.7.27.1 chardet-3.0.4 click-6.7 distlib-0.2.6 functools32-3.2.3.post2 hammock-0.2.4 idna-2.6 jsonschema-2.6.0 requests-2.18.4 urllib3-1.22
	    Installing NPPM (install --ignore-installed --upgrade --root /private/tmp/pip-build-jkLq8A/node.py/nppm --pip-separate-process) ...
	    Installing "@nodepy/nppm@0.0.22"...
	    Installing Python dependencies for "@nodepy/nppm@0.0.22"...
	      Installing Python dependencies via Pip: distlib>=0.2.4 hammock>=0.2.4 jsonschema>=2.6.0 requests>=2.13.0 click>=6.7 appdirs>=1.4.2 --ignore-installed --upgrade (as a separate process)
	    Note: macOS detected, applying homebrew fix (see nodepy/ppym#9)
	          [install] prefix=
	    The directory '/Users/Alex/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	    The directory '/Users/Alex/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
	    Collecting distlib>=0.2.4
	      Downloading distlib-0.2.6.zip (558kB)
	    Collecting hammock>=0.2.4
	      Downloading hammock-0.2.4.tar.gz
	    Collecting jsonschema>=2.6.0
	      Downloading jsonschema-2.6.0-py2.py3-none-any.whl
	    Collecting requests>=2.13.0
	      Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
	    Collecting click>=6.7
	      Downloading click-6.7-py2.py3-none-any.whl (71kB)
	    Collecting appdirs>=1.4.2
	      Downloading appdirs-1.4.3-py2.py3-none-any.whl
	    Collecting functools32; python_version == "2.7" (from jsonschema>=2.6.0)
	      Downloading functools32-3.2.3-2.zip
	    Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13.0)
	      Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
	    Collecting certifi>=2017.4.17 (from requests>=2.13.0)
	      Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
	    Collecting urllib3<1.23,>=1.21.1 (from requests>=2.13.0)
	      Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
	    Collecting idna<2.7,>=2.5 (from requests>=2.13.0)
	      Downloading idna-2.6-py2.py3-none-any.whl (56kB)
	    Installing collected packages: distlib, chardet, certifi, urllib3, idna, requests, hammock, functools32, jsonschema, click, appdirs
	      Running setup.py install for distlib: started
	        Running setup.py install for distlib: finished with status 'done'
	    Exception:
	    Traceback (most recent call last):
	      File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
	        status = self.run(options, args)
	      File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
	        prefix=options.prefix_path,
	      File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
	        **kwargs
	      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
	        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
	      File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
	        isolated=self.isolated,
	      File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 492, in move_wheel_files
	        maker.make_multiple(['%s = %s' % kv for kv in console.items()])
	      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
	        filenames.extend(self.make(specification, options))
	      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
	        self._make_script(entry, filenames, options=options)
	      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
	        self._write_script(scriptnames, shebang, script, filenames, ext)
	      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
	        self._fileop.write_binary_file(outname, script_bytes)
	      File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 407, in write_binary_file
	        with open(path, 'wb') as f:
	    IOError: [Errno 1] Operation not permitted: '/bin/chardetect'
	    Error: `pip install` failed with exit-code 2
	    Error: Installation failed
	    
	    ----------------------------------------
	Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-jkLq8A/node.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-I0O_1Q-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-jkLq8A/node.py/

**Comment by NiklasRosenstein** [comment] 2017-11-03 15:49
That's weird. Unfortunately I can't reproduce this on my Mac. Could you try running `sudo pip install chardet` and see if that works or results in the same error?

**Comment by jzgdev** [comment] 2017-11-04 06:17
No dice with `sudo pip install chardet` but I was finally able to successfully install node.py after uninstalling node.py, wheel, and chardet, then running `pip install node.py --user` 👍🏻

**Comment by NiklasRosenstein** [comment] 2017-11-25 02:10
I'll close this for now, the Node.py 2 installation should be less problematic, especially because the package manager needs to be installed separately. :)

**Closed by NiklasRosenstein** 2017-11-25 02:10 UTC
Labels: bug
